### PR TITLE
add wrapLoading helper function, fix examples, fix logging format, rename spinner to loading

### PR DESCRIPTION
**Pull request by sky-code**
wrapLoading helper function for easy integration of vuex-loading in vue component methods

rename `v-loading` slot `spinner` to `loading` - much more clear what this slot mean

### CODE REVIEW

**Comment by Koc** [comment]
@sky-code nice addition. Can we use this function as decorator? ref #15

**Comment by f** [comment]
Wow this is really a thing, seems neat. I agree with @Koc if that can be a decorator.

**Comment by f** [comment]
I'm going to merge it but won't publish a release for now.

**Comment by f** [comment]
Another use case, maybe we can an extend API for `mapActions` mappings.

```js
...mapLoadingActions('somestore', [
  someRequest: 'something loading',
]);

...

this.someRequest(); // will start loader 'something loading'
```

would be awesome.

**Comment by f** [comment]
@sky-code And I made you a collaborator of this package since your work is awesome for this project, thank you!

**Comment by sky-code** [comment]
@f 

> I'm going to merge it but won't publish a release for now.

why not release? 
v0.4.0 with new feature will be good

**Comment by f** [comment]
@sky-code Ok then, let's do it tonight.

But this library feels me some rewrite for v1.0, I'm not very confident with bundled loaders (I think we should remove them and put just one default spinner) and also not confident with `startLoader` and `endLoader` helpers. Those parts needs to be better. Also we can create `mapLoadingActions` helper for Vuex bindings which would make the library cleaner.

**Comment by sky-code** [comment]
Agree with bundled loaders.
I am not very good in vue internals so I dont know how to Implement `mapLoadingActions`.

**Comment by Koc** [comment]
> rename v-loading slot spinner to loading - much more clear what this slot mean

only one wish: can you add changelog files, please? it is too hard to upgrade between releases.

**Comment by sky-code** [comment]
@Koc https://github.com/f/vuex-loading/blob/master/CHANGELOG.md

**Comment by f** [comment]
0.4.0 is now published.

**Pull request merged**
