### PR TITLE
make vuex optional, big refactoring

### PR DESCRIPTION
**Pull request by sky-code**
Add ability to use VueLoading without vuex.
Plugin refactoring to class (similar to Vuex and vue-router plugins).
Split examples to `default-example` - non vuex usage, and `vuex-example`.
Rename `vuex-loading.js` to `vue-loading.js` (now vuex is optional).
Provide plugin api by injected `$loading` property (similar to Vuex and vue-router plugins).

See also #4 

For testing run `npm run dev-vuex` or `npm run dev-default`

### CODE REVIEW

**Comment by f** [comment]
This is huge :) I need to review it.

**Comment by zawilliams** [comment]
Nice refactor! Just started using this. Anything else need to be done or just waiting for the review?

**Comment by f** [comment]
I haven't check it yet since we're using this in a huge project. Maybe writing a small readme how to migrate from old to new?

**Comment by f** [comment]
MERGED!

**Pull request merged**
